### ISSUE TITLE
uniapp的原生插件封装项目没有开源

### ISSUE THREAD

**Issue by xhb** [openimsdk/open-im-sdk-uniapp#10]
项目只有编译好的二进制文件，没有开源封装项目。如果项目太大，请放到云盘，或是openim的minio上提供下载，不然uniapp用户无法编译使用

**Comment by lgz5689** [comment]
目前已经更新到3.0版本，参考demo实现，https://github.com/OpenIMSDK/Open-IM-Uniapp-Demo
