### ISSUE TITLE
Uniapp SDK 在 IOS 中调用搜索聊天记录 searchLocalMessages API 程序会闪退

### ISSUE THREAD

**Issue by tinypuppet** [openimsdk/open-im-sdk-uniapp#16]
OpenIM SDK 版本：2.3.0.1
这是options参数：{"conversationID":"single_72424","keywordList":[""],"keywordListMatchType":0,"senderUserIDList":[],"messageTypeList":[102],"searchTimePosition":0,"searchTimePeriod":0,"pageIndex":1,"count":50}

**Comment by lgz5689** [comment]
目前已经更新到3.0版本，参考demo实现，https://github.com/OpenIMSDK/Open-IM-Uniapp-Demo
