### ISSUE TITLE
[BUG] uniapp端demo的问题

### ISSUE THREAD

**Issue by hjc1985** [openimsdk/open-im-sdk-uniapp#20]
### OpenIM Server Version

3.8-最新

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

前端在用你们官方uni-app端的demo来测试时，发现登录时，就提示websocket连接不上，这是什么原因？
![1](https://github.com/user-attachments/assets/4d838939-5ae1-4ed7-a48b-37bd9366b9a5)
<img width="609" alt="2" src="https://github.com/user-attachments/assets/f6809579-d948-4a3e-9f03-6670153870cb">
![3](https://github.com/user-attachments/assets/d3150a22-f47b-430c-b381-57c83f8784a4)

**Comment by hjc1985** [comment]
demo的地址：
https://github.com/openimsdk/open-im-uniapp-demo

**Comment by creunies-wanggl** [comment]
> ### OpenIM Server Version
> 3.8-最新
> 
> ### Operating System and CPU Architecture
> Linux (AMD)
> 
> ### Deployment Method
> Docker Deployment
> 
> ### Bug Description and Steps to Reproduce
> 前端在用你们官方uni-app端的demo来测试时，发现登录时，就提示websocket连接不上，这是什么原因？ ![1](https://private-user-images.githubusercontent.com/26477262/364203698-4d838939-5ae1-4ed7-a48b-37bd9366b9a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzAxMjIsIm5iZiI6MTcyNzQyOTgyMiwicGF0aCI6Ii8yNjQ3NzI2Mi8zNjQyMDM2OTgtNGQ4Mzg5MzktNWFlMS00ZWQ3LWE0OGItMzdiZDkzNjZiOWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA5MzcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YWVkY2MxYmVkMTZiYTU5Nzg2ZjI1YTUxN2Q5M2VhM2NmMjM5MWYzOWU0ZDMzYWM5MjJiMDRmZDc3ZmIwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XWhO78h16SHn79ID_tEaUVg2vIkEyXcRp7xPeHwcGwM) <img alt="2" width="609" src="https://private-user-images.githubusercontent.com/26477262/364203944-f6809579-d948-4a3e-9f03-6670153870cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzAxMjIsIm5iZiI6MTcyNzQyOTgyMiwicGF0aCI6Ii8yNjQ3NzI2Mi8zNjQyMDM5NDQtZjY4MDk1NzktZDk0OC00YTNlLTlmMDMtNjY3MDE1Mzg3MGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA5MzcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTljYjQ3ZmJmOGE0ZDdmMTIxNTA5NzBkZTQ0MWU0MzdiYTM2YWNkYmQxZDA4MzM3ZDQzMmYyZjY1ZTY5NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VxgBa85YWpzXsbe11MJxmIiK_bmxFQyOMlrUA6oSBNc"> ![3](https://private-user-images.githubusercontent.com/26477262/364204075-d3150a22-f47b-430c-b381-57c83f8784a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MzAxMjIsIm5iZiI6MTcyNzQyOTgyMiwicGF0aCI6Ii8yNjQ3NzI2Mi8zNjQyMDQwNzUtZDMxNTBhMjItZjQ3Yi00MzBjLWIzODEtNTdjODNmODc4NGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA5MzcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmOWY2ODgyZTk1ODQ2YzFkMTdmYzUzYzBhNWQ4ZmVkZGNhYWE3NzQ5OGM0NTRmZWMyMjAxOTExNzM1ZTgzYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rU0BVv9DAc0z6sQHQ2_9FkgsQSEhI_wCDvmInof_Gso)
> 
> ### Screenshots Link
> _No response_

我也遇到了同样的问题。目前暂未解决。

**Comment by lgz5689** [comment]
3.8.0之后不支持运行H5/小程序，因为jssdk由OIMWS支持，需要退回3.8.0之前的版本。新版本jssdk还未发布。
