### ISSUE TITLE
ios自定义基座打包失败

### ISSUE THREAD

**Issue by creunies-wanggl** [openimsdk/open-im-sdk-uniapp#23]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

android自定义基座成功，ios在mac和winsows10平台自定义基座失败。
信息如下:  2024-11-05 13:52:43    类型: iOS Appstore(真机)    打包失败    错误日志: https://app.liuyingyong.cn/build/errorLog/2cd69400-9b3a-11ef-b19f-3b70acffd3ef

**Comment by lgz5689** [comment]
使用3.8.2,并且不要使用winsows下载、打包ios，只能在ios环境下下载打包。

**Comment by creunies-wanggl** [comment]
> ### OpenIM Server Version
> 3.8.0
> 
> ### Operating System and CPU Architecture
> Windows (AMD)
> 
> ### Deployment Method
> Source Code Deployment
> 
> ### Bug Description and Steps to Reproduce
> android自定义基座成功，ios在mac和winsows10平台自定义基座失败。 信息如下: 2024-11-05 13:52:43 类型: iOS Appstore(真机) 打包失败 错误日志: https://app.liuyingyong.cn/build/errorLog/2cd69400-9b3a-11ef-b19f-3b70acffd3ef
> 
> ### Screenshots Link
> _No response_

关键点是： 如果不是使用的云插件，而是下载到本地，使用nativieplus的时候，要在mac环境中解压缩插件包。因为windows环境没有软链接，造成ios头文件软链接失效，造成打包失败。

**Comment by lgz5689** [comment]
没懂你意思，涉及iOS平台的操作（下载插件、压缩解压等）都不能在winsows环境中操作。

**Comment by creunies-wanggl** [comment]
> 没懂你意思，涉及iOS平台的操作（下载插件、压缩解压等）都不能在winsows环境中操作。

主要是插件，ios的源码有软连接，windows环境会破坏掉。
