### ISSUE TITLE
[BUG] 删除好友后，依然可以正常收发消息

### ISSUE THREAD

**Issue by zhang1832870214** [openimsdk/open-im-sdk-uniapp#25]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Windows (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

我使用uniapp的sdk中的deleteFriend方法进行删除了对方的好友，提示删除成功，好友列表也确实删掉了对方，但是对方依然可以对我发消息，我也能正常对对方发送消息

**Comment by lgz5689** [comment]
正常的，默认用户都能互发消息，非好友不能发消息需要改服务端配置。
