### ISSUE TITLE
[BUG] ios真机闪退：调用 IMSDK.asyncApi( IMSDK.IMMethods.GetSelfUserInfo, IMSDK.uuid() )

### ISSUE THREAD

**Issue by PineSongCN** [openimsdk/open-im-sdk-uniapp#26]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

真机调用以下API后闪退

```
IMSDK.asyncApi(
      IMSDK.IMMethods.GetSelfUserInfo,
      IMSDK.uuid()
)
```

**Comment by lgz5689** [comment]
安卓环境会造成崩溃吗？有没有崩溃相关的日志可以提供？使用的SDK版本是多少？

**Comment by PineSongCN** [comment]
> 安卓环境会造成崩溃吗？有没有崩溃相关的日志可以提供？使用的SDK版本是多少？

安卓没有崩溃，得不到日志，使用的云端打包，版本应该是3.8.2.
asyncApi函数走到如下步骤时ios闪退
```
L[e].apply(
                  L,
                  t.concat([
                    async function (e) {
                      if (0 === e.errCode) {
                        try {
                          e.data = JSON.parse(e.data);
                        } catch (e) {
                          console.log("imsdk:e2", e);
                        }
                        n(e);
                      } else o(e);
                    },
                  ])
                );}
```

**Comment by PineSongCN** [comment]
> 安卓环境会造成崩溃吗？有没有崩溃相关的日志可以提供？使用的SDK版本是多少？

找到原因了，userID传的是数字，安卓正常运行，iOS闪退.....
建议考虑下对userID为数字的情况下抛出错误或者做强制转换。

**Comment by yzzting** [comment]
请问具体是哪里的userID导致的崩溃？我这边也遇到了

**Comment by PineSongCN** [comment]
> 请问具体是哪里的userID导致的崩溃？我这边也遇到了

我这里是登录的时候，强制转字符串，以及如果客户端版本和服务端版本有差别什么的，似乎也会导致闪退
