### ISSUE TITLE
[BUG] searchLocalMessages搜索聊天记录的bug

### ISSUE THREAD

**Issue by zhang1832870214** [openimsdk/open-im-sdk-uniapp#27]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

报错信息：失败,  error *errors.withStack not implement CodeError: SearchMessage failed: no such table: chat_logs_sg_2789475975

**Comment by lgz5689** [comment]
提供服务端版本，客户端版本、客户端SDK版本，如果运行的是安卓平台，请收集相关的logcat日志。
