### ISSUE TITLE
[BUG] 适配新版openim-sdk-core

### ISSUE THREAD

**Issue by zsjinwei** [openimsdk/open-im-sdk-uniapp#28]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

使用新版的[openim-sdk-core](https://github.com/openimsdk/openim-sdk-core), 编译出open_im_sdk.aar后, 放到android目录编译报错:
/Users/huangjinwei/Workspace/Projects/openim-sdk-uniapp/android/openIM/src/main/java/com/example/openim/OpenIMSDK.java:550: 错误: 无法将类 Open_im_sdk中的方法 createImageMessage应用到给定类型;
        return Open_im_sdk.createImageMessage(OperationID, imagePath);
                          ^
  需要: String,String,String,String,String
  找到:    String,String
  原因: 实际参数列表和形式参数列表长度不同
/Users/huangjinwei/Workspace/Projects/openim-sdk-uniapp/android/openIM/src/main/java/com/example/openim/OpenIMSDK.java:567: 错误: 无法将类 Open_im_sdk中的方法 createSoundMessage应用到给定类型;
        return Open_im_sdk.createSoundMessage(OperationID, options.getString("soundPath"), options.getLong("duration"));
                          ^
  需要: String,String,long,String
  找到:    String,String,Long
  原因: 实际参数列表和形式参数列表长度不同
/Users/huangjinwei/Workspace/Projects/openim-sdk-uniapp/android/openIM/src/main/java/com/example/openim/OpenIMSDK.java:588: 错误: 无法将类 Open_im_sdk中的方法 createVideoMessage应用到给定类型;
        return Open_im_sdk.createVideoMessage(OperationID, options.getString("videoPath"), options.getString("videoType"), (long)options.getLong("duration"), options.getString("snapshotPath"));
                          ^
  需要: String,String,String,long,String,String
  找到:    String,String,String,long,String
  原因: 实际参数列表和形式参数列表长度不同
/Users/huangjinwei/Workspace/Projects/openim-sdk-uniapp/android/openIM/src/main/java/com/example/openim/OpenIMSDK.java:609: 错误: 无法将类 Open_im_sdk中的方法 createFileMessage应用到给定类型;
        return Open_im_sdk.createFileMessage(OperationID, options.getString("filePath"), options.getString("fileName"));
                          ^
  需要: String,String,String,String
  找到:    String,String,String
  原因: 实际参数列表和形式参数列表长度不同
/Users/huangjinwei/Workspace/Projects/openim-sdk-uniapp/android/openIM/src/main/java/com/example/openim/OpenIMSDK.java:727: 错误: 找不到符号
        Open_im_sdk.sendMessageNotOss(sendMsgNotOssCallBack, operationID, messageStr, options.getString("recvID"), options.getString("groupID"), offlinePushInfoStr, isOnlineOnly);
                   ^
  符号:   方法 sendMessageNotOss(SendMsgCallBack,String,String,String,String,String,boolean)
  位置: 类 Open_im_sdk
注: /Users/huangjinwei/Workspace/Projects/openim-sdk-uniapp/android/openIM/src/main/java/com/example/openim/OpenIMSDK.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

似乎是openim-sdk-core部分接口已经移除或改动, 什么时候可以更新一下这个库?

**Comment by lgz5689** [comment]
最新的openim-sdk-core还是在beta测试环节，还不是正式版本。等发布了正式版本才会更想。

**Comment by lgz5689** [comment]
具体参考 https://github.com/openimsdk/openim-sdk-core/releases
