### ISSUE TITLE
 uniapp端调用删除消息后的异常

### ISSUE THREAD

**Issue by AirJain** [openimsdk/open-im-sdk-uniapp#29]
### What would you like to share?

比如聊天记录总数总数据100条 进入消息列表我传的count是20第一次加载返回了20条 然后删除这20条里的某条消息  返回聊天列表后再进入 就只返回19条
deleteMessage
删除接口
GetAdvancedHistoryMessageList
消息列表接口

**Comment by lgz5689** [comment]
提供服务端版本，客户端版本、客户端SDK版本，如果运行的是安卓平台，请收集相关的logcat日志。

**Comment by AirJain** [comment]
服务端： server:3.8.1
客户端：[3](https://github.com/openimsdk/open-im-sdk-uniapp)
SDK版本：3.8.2
日志：
[open-im-sdk-core (3).txt](https://github.com/user-attachments/files/17971727/open-im-sdk-core.3.txt)
对应消息记录列表：
每次返回的count都是20-被删除消息的数量
对应operationID：
53f80d9d-a0ba-4321-8e18-75aa728e0b78
236ebe7f-7d68-4478-b870-81738e5e78eb
5809961c-ab44-4ff6-966a-bbc8cd730bb1
0ea0ca50-8ac5-4b87-bff4-988d8b395148

**Comment by lgz5689** [comment]
@FGadvancer

**Comment by lgz5689** [comment]
目前sdk确实存在这个问题，建议参考 https://docs.openim.io/zh-Hans/sdks/class/message/advancedHistoryInfo 使用 isEnd 判断是否拉取到所有的消息。
