### ISSUE TITLE
[Other]: 我看DCloud插件市场已经更新到3.8.2, 这个代码库可否更新一下

### ISSUE THREAD

**Issue by zsjinwei** [openimsdk/open-im-sdk-uniapp#31]
### What would you like to share?

如 #28 所述, 3.8.2 已经release, 这个代码库可否更新一下适配3.8.2?

**Comment by lgz5689** [comment]
#28 是自己用了 3.9 的内容，和 3.8.2 没有关系。3.8.1 - 3.8.2 SDK中间层内容基本没有修改。
