### ISSUE TITLE
macbook下ios云打包原生插件失败

### ISSUE THREAD

**Issue by zsden** [OpenIMSDK/Open-IM-SDK-Uniapp#4]
![image](https://user-images.githubusercontent.com/31877252/146488299-539e3ff4-3608-46f6-ad94-3a4e2bbca49a.png)
图中链接：https://ide.dcloud.net.cn/build/errorLog/717789d0-5eeb-11ec-9536-4787ca92d69e
插件配置
![image](https://user-images.githubusercontent.com/31877252/146488431-be44cf92-7e8d-4ad3-8d47-46063630eb26.png)

**Comment by Bloomingg** [comment]
拉取最新SDK重新打包尝试一下，或者稍后uniapp插件市场审核通过后通过云端插件1.0.4打包https://ext.dcloud.net.cn/plugin?id=6577

**Comment by zsden** [comment]
我试了，可以了
