### ISSUE TITLE
请教几个关于消息的问题

### ISSUE THREAD

**Issue by ctycode** [openimsdk/open-im-sdk-uniapp#8]
感谢开源，有两个问题想要咨询下， 我使用uniapp的OpenIM原生插件
1.当接收到新消息时，原生插件会自动缓存新消息内容吗？
2.聊天页获取数据的正确逻辑是什么？目前我都是全局监听新消息，然后进入了聊天页面之后在通过getHistoryMessageList加载聊天内容。

**Comment by ctycode** [comment]
还有一个就是离线推送的问题，离线推送的clientId就是用户userID吗？

**Comment by ctycode** [comment]
还有就是我修改服务端的代码 重启docker之后修改的内容不生效 没用过docker这里是需要什么其他的操作吗？

**Comment by lgz5689** [comment]
目前已经更新到3.0版本，参考demo实现，https://github.com/OpenIMSDK/Open-IM-Uniapp-Demo
